### ISSUE TITLE
npm install error no git access

### ISSUE THREAD

**Issue by jericopulvera** [triestpa/chess-frontend#1]
npm ERR! Error while executing:
npm ERR! C:\laragon\bin\git\bin\git.EXE ls-remote -h -t ssh://git@github.com/jhlywa/chess.js.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ECO\AppData\Roaming\npm-cache\_logs\2018-01-11T11_27_30_617Z-debug.log

**Comment by triestpa** [comment]
Thanks for noticing this @jericopulvera - it should be fixed now.  It seems that the `chess.js` git installation config in the `package-lock.json` file was causing issues.
